In [1]:
from functions import *

In [2]:
val = []

In [3]:
ar0= np.array([
    [0, 1, 0, 1, 0, 0],
    [1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 0],
    [0, 2, 0, 0, 0, 0],
    [2, 0, 2, 0, 1, 0],
    [2, 0, 2, 1, 0, 1],
    [0, 2, 0, 1, 1, 1]
])

In [4]:
ar1 = np.array(
    [[3,3,3,3,3],[3,2,2,2,3],[3,2,1,2,3],[3,2,2,2,3],[3,3,3,3,3]]
)

In [5]:
ar2 = np.array([
    [1,4,3,1,3,2],
    [3,2,1,3,2,4],
    [2,3,3,2,3,1]
    ])

In [6]:
def main(ar_in):
    cn = 0
    ar = ar_in.copy()
    x, y = np.shape(ar)
    iter = 0
    tvol = 0

    while np.any(ar != 0):
        iter +=1
        for i in range(1, x-1):
            for j in range(1, y-1):
                #If a zero is detected then initiate flood fill, which replaces all bordering 0s with a different number, e.g 11
                if ar[i, j] == 0:

                    val.append( iter*(2**i + 10*j) ) #it needs a better unique value generator but it will do for now
                    ar = flood_fill(ar, i, j, val[cn])

                    check, vol = calc(ar, val[cn])
                    if check == False:
                        tvol += vol
                    cn += 1
        print(ar)
        ar = rlevel(ar_in, iter)
    return tvol

In [7]:
main(ar2)

[[1 4 3 1 3 2]
 [3 2 1 3 2 4]
 [2 3 3 2 3 1]]
[[ 0  3  2  0  2  1]
 [ 2  1 44  2  1  3]
 [ 1  2  2  1  2  0]]
[[  0   2   1   0   1   0]
 [  1  36  36   1 126   2]
 [  0   1   1   0   1   0]]
[[48  1 48 48 48 48]
 [48 48 48 48 48  1]
 [48 48 48 48 48 48]]


4